model_list:
  # 1. Meta Llama 3
  - model_name: bedrock-llama
    litellm_params:
      model: bedrock/meta.llama3-8b-instruct-v1:0
      aws_region_name: us-east-1
    
  # 2. Amazon Titan Express
  - model_name: bedrock-titan
    litellm_params:
      model: bedrock/amazon.titan-text-express-v1
      aws_region_name: us-east-1

  # 3. Amazon Titan Lite
  - model_name: bedrock-titan-lite
    litellm_params:
      model: bedrock/amazon.titan-text-lite-v1
      aws_region_name: us-east-1

  # 4. Cohere Command R
  - model_name: bedrock-cohere
    litellm_params:
      model: bedrock/cohere.command-r-v1:0
      aws_region_name: us-east-1

litellm_settings:
  drop_params: true
